spring:
  application:
    name: SOAPGateway
  datasource:
    url: jdbc:h2:file:./data/soapgatewaydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080

gateway:
  storage:
    persist-request-xml: true
  downstream:
    endpoint-url: http://localhost:8081/ws/business
    soap-action:
  external:
    endpoint-url: http://localhost:8082/ws/external
    soap-action:
